const funkyEmojis = [
    {
        "description": "abakule",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/abakule/ae1a8a65cc7842a3.png",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01BY0ZB84Q",
        "created": 1600981640,
        "is_bad": false,
        "user_display_name": "Adrian",
        "avatar_hash": "75d9040cf11a",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "aba_akklamasjon",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/aba_akklamasjon/9bdd66da88b91ed9.png",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01BY0ZB84Q",
        "created": 1600981813,
        "is_bad": false,
        "user_display_name": "Adrian",
        "avatar_hash": "75d9040cf11a",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "aca-scuse-me",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/aca-scuse-me/7eaa17393bf5f152.png",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01BF5L2FPW",
        "created": 1668523178,
        "is_bad": false,
        "user_display_name": "Lars",
        "avatar_hash": "a0235e05968d",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "andrine",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/andrine/244607ad0f895cbe.png",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01BY0ZB84Q",
        "created": 1666524280,
        "is_bad": false,
        "user_display_name": "Adrian",
        "avatar_hash": "75d9040cf11a",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "bergen",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/bergen/acf9e8275bba1937.png",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01B7GT8FC5",
        "created": 1653236272,
        "is_bad": false,
        "user_display_name": "Redrei",
        "avatar_hash": "1b246df9b9c0",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "bigbrother",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/bigbrother/9c668df28113e983.jpg",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01B7GT8FC5",
        "created": 1612174499,
        "is_bad": false,
        "user_display_name": "Redrei",
        "avatar_hash": "1b246df9b9c0",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "blob_dance",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/blob_dance/3b2d61655fe0f503.gif",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01AXE5JD7Z",
        "created": 1629702646,
        "is_bad": false,
        "user_display_name": "Espen",
        "avatar_hash": "1bb6bb2fb9ef",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "bouncing_parrot",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/bouncing_parrot/55ea8069447a01b3.gif",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01AXE5JD7Z",
        "created": 1629702512,
        "is_bad": false,
        "user_display_name": "Espen",
        "avatar_hash": "1bb6bb2fb9ef",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "brainntnu",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/brainntnu/dc8cec2a1381e552.png",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01AXE5JD7Z",
        "created": 1602167213,
        "is_bad": false,
        "user_display_name": "Espen",
        "avatar_hash": "1bb6bb2fb9ef",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "c++",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/c%252B%252B/c9e13201807ed03f.png",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01B7GT8FC5",
        "created": 1601922907,
        "is_bad": false,
        "user_display_name": "Redrei",
        "avatar_hash": "1b246df9b9c0",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "clique",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/clique/7b47601242a36356.png",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01BY0ZB84Q",
        "created": 1657711749,
        "is_bad": false,
        "user_display_name": "Adrian",
        "avatar_hash": "75d9040cf11a",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "cogito",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/cogito/9776e3f86b5e1cf1.png",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01AXE5JD7Z",
        "created": 1601412716,
        "is_bad": false,
        "user_display_name": "Espen",
        "avatar_hash": "1bb6bb2fb9ef",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "come-into-my-bed",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/come-into-my-bed/c5da611cf9d310b5.jpg",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01BF5L2FPW",
        "created": 1661963552,
        "is_bad": false,
        "user_display_name": "Lars",
        "avatar_hash": "a0235e05968d",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "dancing",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/dancing/101b0b40a1a863df.png",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01BY0ZB84Q",
        "created": 1666893104,
        "is_bad": false,
        "user_display_name": "Adrian",
        "avatar_hash": "75d9040cf11a",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "deutschland",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/deutschland/33f66d688ab090c4.png",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01B7GT8FC5",
        "created": 1601927774,
        "is_bad": false,
        "user_display_name": "Redrei",
        "avatar_hash": "1b246df9b9c0",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "devil",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/devil/ce0d844b95a64245.png",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01BY0ZB84Q",
        "created": 1666893511,
        "is_bad": false,
        "user_display_name": "Adrian",
        "avatar_hash": "75d9040cf11a",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "doubt",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/doubt/44e855a4fb99afe4.jpg",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01ATDNKQUX",
        "created": 1639405024,
        "is_bad": false,
        "user_display_name": "Mathias",
        "avatar_hash": "bffaf8a83732",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "duck_dance",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/duck_dance/4410b77942bdf7a8.gif",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01AXE5JD7Z",
        "created": 1664027100,
        "is_bad": false,
        "user_display_name": "Espen",
        "avatar_hash": "1bb6bb2fb9ef",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "ektekjaerlighet",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/ektekjaerlighet/a432d85affc8edc4.png",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01BY0ZB84Q",
        "created": 1657711283,
        "is_bad": false,
        "user_display_name": "Adrian",
        "avatar_hash": "75d9040cf11a",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "emilio",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/emilio/6ae1e23fc8e332bb.png",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01BF5L2FPW",
        "created": 1610972420,
        "is_bad": false,
        "user_display_name": "Lars",
        "avatar_hash": "a0235e05968d",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "emilioland",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/emilioland/591a1a2d5bb64177.png",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01BF5L2FPW",
        "created": 1610973080,
        "is_bad": false,
        "user_display_name": "Lars",
        "avatar_hash": "a0235e05968d",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "espen",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/espen/4eee5223bf73f760.jpg",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01BY0ZB84Q",
        "created": 1600889970,
        "is_bad": false,
        "user_display_name": "Adrian",
        "avatar_hash": "75d9040cf11a",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "exceptionally_fast_parrot",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/exceptionally_fast_parrot/c50bbf0d987ffcd2.gif",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01AXE5JD7Z",
        "created": 1629702445,
        "is_bad": false,
        "user_display_name": "Espen",
        "avatar_hash": "1bb6bb2fb9ef",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "fakenews",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/fakenews/d159fe6ef1413225.png",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01BY0ZB84Q",
        "created": 1600981880,
        "is_bad": false,
        "user_display_name": "Adrian",
        "avatar_hash": "75d9040cf11a",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "finn",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/finn/ed610aef8fa56cd8.png",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01BY0ZB84Q",
        "created": 1610738403,
        "is_bad": false,
        "user_display_name": "Adrian",
        "avatar_hash": "75d9040cf11a",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "gecko",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/gecko/c34140f34be5f93a.jpg",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01B7GT8FC5",
        "created": 1601922859,
        "is_bad": false,
        "user_display_name": "Redrei",
        "avatar_hash": "1b246df9b9c0",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "gempire",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/gempire/6300d178b7cf1fbb.png",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01ATDNKQUX",
        "created": 1610961478,
        "is_bad": false,
        "user_display_name": "Mathias",
        "avatar_hash": "bffaf8a83732",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "gitcod",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/gitcod/774ba25700bb7511.png",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01BF5L2FPW",
        "created": 1600943282,
        "is_bad": false,
        "user_display_name": "Lars",
        "avatar_hash": "a0235e05968d",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "grill",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/grill/97cdedf8ed67e83f.png",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01BY0ZB84Q",
        "created": 1657710316,
        "is_bad": false,
        "user_display_name": "Adrian",
        "avatar_hash": "75d9040cf11a",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "hereugo",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/hereugo/3d297c3a97115fa6.png",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01BY0ZB84Q",
        "created": 1657710662,
        "is_bad": false,
        "user_display_name": "Adrian",
        "avatar_hash": "75d9040cf11a",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "houseofdotclique",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/houseofdotclique/4e4ff547a2069e22.png",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01BY0ZB84Q",
        "created": 1663542752,
        "is_bad": false,
        "user_display_name": "Adrian",
        "avatar_hash": "75d9040cf11a",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "hunk-i-bar-overkropp",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/hunk-i-bar-overkropp/53d0d68deaf1e05d.png",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01BF5L2FPW",
        "created": 1661374704,
        "is_bad": false,
        "user_display_name": "Lars",
        "avatar_hash": "a0235e05968d",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "idk",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/idk/30028e11dd5bf5fe.jpg",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01BY0ZB84Q",
        "created": 1600976873,
        "is_bad": false,
        "user_display_name": "Adrian",
        "avatar_hash": "75d9040cf11a",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "ifix",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/ifix/a154c1a75b60e6c2.png",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01BY0ZB84Q",
        "created": 1657710958,
        "is_bad": false,
        "user_display_name": "Adrian",
        "avatar_hash": "75d9040cf11a",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "jorgen",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/jorgen/45e2a7a147667334.png",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01BY0ZB84Q",
        "created": 1657710006,
        "is_bad": false,
        "user_display_name": "Adrian",
        "avatar_hash": "75d9040cf11a",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "julius",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/julius/9e7cd0fa59061a7e.jpg",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01B7GT8FC5",
        "created": 1601923000,
        "is_bad": false,
        "user_display_name": "Redrei",
        "avatar_hash": "1b246df9b9c0",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "kok",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/kok/8ec5a8dfae2d002f.jpg",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01BF5L2FPW",
        "created": 1600943680,
        "is_bad": false,
        "user_display_name": "Lars",
        "avatar_hash": "a0235e05968d",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "lamainmylivingroom",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/lamainmylivingroom/d75ec12744bff6d7.png",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01BY0ZB84Q",
        "created": 1657711158,
        "is_bad": false,
        "user_display_name": "Adrian",
        "avatar_hash": "75d9040cf11a",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "lars",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/lars/a75b9313aae90b02.png",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01BY0ZB84Q",
        "created": 1657710311,
        "is_bad": false,
        "user_display_name": "Adrian",
        "avatar_hash": "75d9040cf11a",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "linguini",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/linguini/1127d15eac27091a.jpg",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01B7GT8FC5",
        "created": 1634403070,
        "is_bad": false,
        "user_display_name": "Redrei",
        "avatar_hash": "1b246df9b9c0",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "luffymad",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/luffymad/bd952c14094fcd76.jpg",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01AU7AC7LP",
        "created": 1600978388,
        "is_bad": false,
        "user_display_name": "Ulrik",
        "avatar_hash": "9bc9f1261929",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "luffy_smile",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/luffy_smile/ccdd5e0e7e4b0886.jpg",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01AU7AC7LP",
        "created": 1619116451,
        "is_bad": false,
        "user_display_name": "Ulrik",
        "avatar_hash": "9bc9f1261929",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "meow_amongus",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/meow_amongus/217aca95e1807365.png",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01AXE5JD7Z",
        "created": 1657920394,
        "is_bad": false,
        "user_display_name": "Espen",
        "avatar_hash": "1bb6bb2fb9ef",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "meow_angry-intensifies",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/meow_angry-intensifies/a193d439c44acf09.gif",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01AXE5JD7Z",
        "created": 1633098954,
        "is_bad": false,
        "user_display_name": "Espen",
        "avatar_hash": "1bb6bb2fb9ef",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "meow_attention",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/meow_attention/93f942fa3ddd0fd6.png",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01AXE5JD7Z",
        "created": 1633098962,
        "is_bad": false,
        "user_display_name": "Espen",
        "avatar_hash": "1bb6bb2fb9ef",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "meow_code",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/meow_code/0bdbb6ced9e51771.gif",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01AXE5JD7Z",
        "created": 1633098931,
        "is_bad": false,
        "user_display_name": "Espen",
        "avatar_hash": "1bb6bb2fb9ef",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "meow_crying",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/meow_crying/aba96c6f8faaeef5.gif",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01AXE5JD7Z",
        "created": 1633529079,
        "is_bad": false,
        "user_display_name": "Espen",
        "avatar_hash": "1bb6bb2fb9ef",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "meow_devil-intensifies",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/meow_devil-intensifies/ae90b8c685a56fa3.gif",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01AXE5JD7Z",
        "created": 1666190396,
        "is_bad": false,
        "user_display_name": "Espen",
        "avatar_hash": "1bb6bb2fb9ef",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "meow_dundundun",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/meow_dundundun/d69364c0bff594af.gif",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01AXE5JD7Z",
        "created": 1633529067,
        "is_bad": false,
        "user_display_name": "Espen",
        "avatar_hash": "1bb6bb2fb9ef",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "meow_fat",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/meow_fat/d814be1974cf9e21.gif",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01AXE5JD7Z",
        "created": 1643011329,
        "is_bad": false,
        "user_display_name": "Espen",
        "avatar_hash": "1bb6bb2fb9ef",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "meow_mustache",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/meow_mustache/4c8f1561239f8366.png",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01BF5L2FPW",
        "created": 1663334014,
        "is_bad": false,
        "user_display_name": "Lars",
        "avatar_hash": "a0235e05968d",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "meow_nerd",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/meow_nerd/af3ee4b95db2d552.png",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01AXE5JD7Z",
        "created": 1643011176,
        "is_bad": false,
        "user_display_name": "Espen",
        "avatar_hash": "1bb6bb2fb9ef",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "meow_noddies",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/meow_noddies/19f823396f7993df.gif",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01AXE5JD7Z",
        "created": 1633098976,
        "is_bad": false,
        "user_display_name": "Espen",
        "avatar_hash": "1bb6bb2fb9ef",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "meow_outage",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/meow_outage/43f3fcde07952085.png",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01AXE5JD7Z",
        "created": 1643011611,
        "is_bad": false,
        "user_display_name": "Espen",
        "avatar_hash": "1bb6bb2fb9ef",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "meow_party",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/meow_party/3d808b807f8150f5.gif",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01AXE5JD7Z",
        "created": 1629702570,
        "is_bad": false,
        "user_display_name": "Espen",
        "avatar_hash": "1bb6bb2fb9ef",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "meow_sip",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/meow_sip/1d9e84318abc7cfb.png",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01AXE5JD7Z",
        "created": 1633098945,
        "is_bad": false,
        "user_display_name": "Espen",
        "avatar_hash": "1bb6bb2fb9ef",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "meow_stare",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/meow_stare/ca9b4823ff571687.png",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01AXE5JD7Z",
        "created": 1643011252,
        "is_bad": false,
        "user_display_name": "Espen",
        "avatar_hash": "1bb6bb2fb9ef",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "meow_suit",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/meow_suit/68af378c9172c1f2.png",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01AXE5JD7Z",
        "created": 1666190383,
        "is_bad": false,
        "user_display_name": "Espen",
        "avatar_hash": "1bb6bb2fb9ef",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "neitiloslo",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/neitiloslo/e6488b779f074f20.png",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01BF5L2FPW",
        "created": 1601371536,
        "is_bad": false,
        "user_display_name": "Lars",
        "avatar_hash": "a0235e05968d",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "notwindows",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/notwindows/a94c152fed92286a.png",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01B963JQ2F",
        "created": 1647525892,
        "is_bad": false,
        "user_display_name": "Gjørgen",
        "avatar_hash": "060f3204b02e",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "ompatildudor",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/ompatildudor/13d666e58e9c500c.jpg",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01B7GT8FC5",
        "created": 1667985006,
        "is_bad": false,
        "user_display_name": "Redrei",
        "avatar_hash": "1b246df9b9c0",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "oof",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/oof/bb5ef4817f68b392.png",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01BY0ZB84Q",
        "created": 1600981682,
        "is_bad": false,
        "user_display_name": "Adrian",
        "avatar_hash": "75d9040cf11a",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "out_of_scope",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/out_of_scope/0818326b307b580d.jpg",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01ATDNKQUX",
        "created": 1606819656,
        "is_bad": false,
        "user_display_name": "Mathias",
        "avatar_hash": "bffaf8a83732",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "party_parrot",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/party_parrot/c630f53c92d6216a.gif",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01AXE5JD7Z",
        "created": 1629702372,
        "is_bad": false,
        "user_display_name": "Espen",
        "avatar_hash": "1bb6bb2fb9ef",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "pernaa",
        "is_alias": 1,
        "alias_for": "pernod",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/pernod/3466ff3804164abd.png",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01ATDNKQUX",
        "created": 1670979934,
        "is_bad": false,
        "user_display_name": "Mathias",
        "avatar_hash": "bffaf8a83732",
        "can_delete": true,
        "synonyms": [
            "pernaa",
            "pernod"
        ]
    },
    {
        "description": "pernod",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/pernod/3466ff3804164abd.png",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01ATDNKQUX",
        "created": 1670979913,
        "is_bad": false,
        "user_display_name": "Mathias",
        "avatar_hash": "bffaf8a83732",
        "can_delete": true,
        "synonyms": [
            "pernaa",
            "pernod"
        ]
    },
    {
        "description": "pr",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/pr/6f6897c7f21a6f4e.png",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01BY0ZB84Q",
        "created": 1600981750,
        "is_bad": false,
        "user_display_name": "Adrian",
        "avatar_hash": "75d9040cf11a",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "product_placement",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/product_placement/93616d41a87bb62d.png",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01ATDNKQUX",
        "created": 1610961027,
        "is_bad": false,
        "user_display_name": "Mathias",
        "avatar_hash": "bffaf8a83732",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "proud",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/proud/87df8cbf0872d5b0.png",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01BY0ZB84Q",
        "created": 1657710834,
        "is_bad": false,
        "user_display_name": "Adrian",
        "avatar_hash": "75d9040cf11a",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "purre",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/purre/51d22795dcbfcfca.png",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01BY0ZB84Q",
        "created": 1634226587,
        "is_bad": false,
        "user_display_name": "Adrian",
        "avatar_hash": "75d9040cf11a",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "readme",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/readme/4e360a2e6244c5fa.png",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01BY0ZB84Q",
        "created": 1600981728,
        "is_bad": false,
        "user_display_name": "Adrian",
        "avatar_hash": "75d9040cf11a",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "reddit",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/reddit/4598c16373c43114.png",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01BY0ZB84Q",
        "created": 1610738668,
        "is_bad": false,
        "user_display_name": "Adrian",
        "avatar_hash": "75d9040cf11a",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "resigned_yang",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/resigned_yang/9244504706bdfb9d.png",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01BF5L2FPW",
        "created": 1625084891,
        "is_bad": false,
        "user_display_name": "Lars",
        "avatar_hash": "a0235e05968d",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "reverse_strawhat",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/reverse_strawhat/53b05c59b62b296c.jpg",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01AU7AC7LP",
        "created": 1619170512,
        "is_bad": false,
        "user_display_name": "Ulrik",
        "avatar_hash": "9bc9f1261929",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "rip",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/rip/1a15926ea816d040.png",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01BY0ZB84Q",
        "created": 1610738254,
        "is_bad": false,
        "user_display_name": "Adrian",
        "avatar_hash": "75d9040cf11a",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "run",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/run/8f47c48b6621d8a5.png",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01BY0ZB84Q",
        "created": 1657709777,
        "is_bad": false,
        "user_display_name": "Adrian",
        "avatar_hash": "75d9040cf11a",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "sit-rezervo-working",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/sit-rezervo-working/c114a5945f19e1be.gif",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01ATDNKQUX",
        "created": 1671563433,
        "is_bad": false,
        "user_display_name": "Mathias",
        "avatar_hash": "bffaf8a83732",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "spqr",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/spqr/ce7594fa94d8b3f5.png",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01B7GT8FC5",
        "created": 1601922689,
        "is_bad": false,
        "user_display_name": "Redrei",
        "avatar_hash": "1b246df9b9c0",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "sykkeltur",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/sykkeltur/0ce11a9ccafdf653.png",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01BY0ZB84Q",
        "created": 1657711050,
        "is_bad": false,
        "user_display_name": "Adrian",
        "avatar_hash": "75d9040cf11a",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "towl",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/towl/99fb95d2296d8a72.png",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01ATDNKQUX",
        "created": 1600889877,
        "is_bad": false,
        "user_display_name": "Mathias",
        "avatar_hash": "bffaf8a83732",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "triumvirati",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/triumvirati/870a21411bcd8608.jpg",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01BY0ZB84Q",
        "created": 1600890476,
        "is_bad": false,
        "user_display_name": "Adrian",
        "avatar_hash": "75d9040cf11a",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "uhoh",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/uhoh/ef1c2153db024a4e.jpg",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01BF5L2FPW",
        "created": 1635110961,
        "is_bad": false,
        "user_display_name": "Lars",
        "avatar_hash": "a0235e05968d",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "vim",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/vim/8b159c26f231bcc7.png",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01BY0ZB84Q",
        "created": 1610738044,
        "is_bad": false,
        "user_display_name": "Adrian",
        "avatar_hash": "75d9040cf11a",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "webkom",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/webkom/19a50b5d7b7ea405.png",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01BY0ZB84Q",
        "created": 1600981767,
        "is_bad": false,
        "user_display_name": "Adrian",
        "avatar_hash": "75d9040cf11a",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "weedme",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/weedme/8787a91b1732425b.png",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01BY0ZB84Q",
        "created": 1600981611,
        "is_bad": false,
        "user_display_name": "Adrian",
        "avatar_hash": "75d9040cf11a",
        "can_delete": true,
        "synonyms": []
    },
    {
        "description": "works-on-my-machine",
        "is_alias": 0,
        "alias_for": "",
        "emoji": "https://emoji.slack-edge.com/T01B8BQ1KNF/works-on-my-machine/8844e941fc73cdfe.png",
        "team_id": "T01B8BQ1KNF",
        "user_id": "U01BF5L2FPW",
        "created": 1643228258,
        "is_bad": false,
        "user_display_name": "Lars",
        "avatar_hash": "a0235e05968d",
        "can_delete": true,
        "synonyms": []
    }
]

export default funkyEmojis;
